version: "3.9"

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    networks:
      - pasantia_my_network
    environment:
      - DEBUG=1
      - DJANGO_SECRET_KEY=django-insecure-3+8w0)k(w6+0-s#2six43-r^9bnwg&u5aioqvt+uo4=o8v4ad8
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
    depends_on:
      - db
    #entrypoint: ["./wait-for-it.sh", "db:5432", "--", "python", "manage.py", "runserver", "0.0.0.0:8000"]
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    ports:
      - "5432:5432"
    networks:
      - pasantia_my_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/django_db
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    command: 
      - start-dev
    networks:
      - pasantia_my_network

volumes:
  postgres_data:

networks:
  pasantia_my_network:
    external: true
    driver: bridge